### ISSUE TITLE
Question about job_name and logic_name

### ISSUE THREAD

**Issue by Wang-Kangjin** [google/cluster-data#19]
I found that  `job_name` and `logic_name` have a many-to-one relationship. So..for two jobs with the same `logic_name` but have different `job_name`, What are their same and different? I know they have the same code. But what's the difference about their input data size?
Looking for your reply. Thanks!

**Comment by johnwilkes** [comment]
An example of this could be auto-generated, periodic MapReduce jobs.  As
you note, they will run the same code, but different jobs will consume
different inputs - e.g., on different days.
