### ISSUE TITLE
wrong timestamp format

### ISSUE THREAD

**Issue by usman9114** [google/cluster-data#22]
Hi,
Could you please explain how to format timestamp (start & end time). When i query start date from table it returns me following unix timestamp.

Unix 2076900000000 -> UTC Thu Oct 25 2035 04:40:00
1500120000000 -> UTC Sat Jul 15 2017 12:00:00

According to table, data should contain observations from 2019.

**Comment by monnand** [comment]
This is by design. The time in the trace starts from 0. It is not UNIX timestamp. The trace [document](https://drive.google.com/file/d/10r6cnJ5cJ89fPWCgj7j4LtLBqYN9RiI9/view) discussed more details about time and timestamp.
