### ISSUE TITLE
Sample portion for all records equal to zero

### ISSUE THREAD

**Issue by rieglerthomas** [google/cluster-data#27]
Hello,

I have noticed that no record for the task usage contains a sample portion which is non-zero. I have verified this programatically. According to the format & schema document, this field represents the ratio of excepted to observed samples during a measurement period. So, it should not be the case that this is zero for all records. Why is that the case regardless?

**Comment by Tephen** [comment]
I meet same problem. Could you please tell me how you solve this?

**Comment by johnwilkes** [comment]
Hi. If you'd still like a response to this question, please ask it on the mailing list: https://groups.google.com/g/googleclusterdata-discuss.  Thanks.
