### ISSUE TITLE
Priority of the Best-effort Batch (beb) tier jobs

### ISSUE THREAD

**Issue by lapisliu** [google/cluster-data#30]
In the [Google cluster-usage traces v3](https://drive.google.com/file/d/10r6cnJ5cJ89fPWCgj7j4LtLBqYN9RiI9/view) document, the priority range of Beb jobs is 100-115, whereas it is given as 110-115, in the _Borg: the Next Generation_ paper and the paper does not mention how those between 100-110 are included. Which one is correct? And does that mean those between 100 and 110 are not included as a part of the paper's analysis?

Thanks!

**Comment by johnwilkes** [comment]
Hi. If you'd still like a response to this question, please ask it on the mailing list: https://groups.google.com/g/googleclusterdata-discuss.  Thanks.
