### ISSUE TITLE
Assigned Local Disk Space data missing

### ISSUE THREAD

**Issue by PannaAryan** [google/cluster-data#35]
Google Cluster 2011-2 dataset
**_**Assigned Local Disk Space**_** data is missing in this dataset.

**Comment by johnwilkes** [comment]
I have no idea what this means.  Please can you elaborate?

**Comment by johnwilkes** [comment]
Hi. If you'd still like a response to this question, please ask it on the mailing list: https://groups.google.com/g/googleclusterdata-discuss.  Thanks.
